# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c7709f4e3707254c99aea490d06c67f72bba47b790c76d18271083a55c9a2b2cf19eccf869f9eabd92b14233071dafa1e093404ce05f92c109ed1fcdfd7971c

test:
  secret_key_base: 7900b7ce815008aabefa34116a5c7f2c9e899fd7bb8c64071dacd286118cde6ba64e5fee60e322494a4fd45221e58eaf58f270283f091e66df276f745847b3d5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
